### PR TITLE
1st CL for readability improvement

### PR DESCRIPTION
**Pull request by MaryamZaheri**

### CODE REVIEW

**Comment by armintoepfer** [comment]
Do we use different variable naming schemes throughout the code base or why the renaming from one convention to another?

**Comment by MaryamZaheri** [comment]
I am making the code consistent with the most often used format, and will continue this on other files.

**Comment by armintoepfer** [comment]
The most often used format within HaploClique or in C++land?

**Comment by MaryamZaheri** [comment]
in HaploClique.

**Comment by MaryamZaheri** [comment]
Hi Armin, what is the decision regarding this pull request?

**Comment by armintoepfer** [comment]
Please see the comment that you haven't addressed yet.

**Comment by MaryamZaheri** [comment]
I submitted a minor version as a draft. Please let me know if you have any comment.

**Comment by armintoepfer** [comment]
Just increase the version in the CMakeLists.txt, how hard can that be?

**Comment by MaryamZaheri** [comment]
Done.

**Comment by armintoepfer** [comment]
no

After 1.0.1 comes 1.1.0

**Comment by MaryamZaheri** [comment]
Sorry for the typo. Fixed.

**Pull request merged**
